# Generated by Django 5.0.2 on 2024-03-05 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0002_loanitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanItem',
        ),
    ]
