# Generated by Django 5.0.2 on 2024-03-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0002_customuser_loan_owed_loan_loanrepayment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='savings',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='Users',
        ),
        migrations.AlterModelTable(
            name='item',
            table='Items',
        ),
        migrations.AlterModelTable(
            name='loan',
            table='Loans',
        ),
        migrations.AlterModelTable(
            name='loanrepayment',
            table='Loan_Repayments',
        ),
        migrations.AlterModelTable(
            name='loantransaction',
            table='Loan_Transactions',
        ),
        migrations.AlterModelTable(
            name='paymentmethod',
            table='Payment_Methods',
        ),
        migrations.AlterModelTable(
            name='savings',
            table='Savings_Accounts',
        ),
        migrations.AlterModelTable(
            name='savingsitem',
            table='Savings_Items',
        ),
        migrations.AlterModelTable(
            name='savingstransaction',
            table='Savings_Transactions',
        ),
        migrations.AlterModelTable(
            name='trustscore',
            table='TrustScore',
        ),
    ]
