# Generated by Django 5.0.2 on 2024-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0002_remove_customuser_trustscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idnumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
