# Generated by Django 5.0.2 on 2024-03-06 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0003_alter_customuser_options_alter_savings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingstransaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='savings_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='newmamapesa.savingsitem'),
        ),
    ]
