# Generated by Django 5.0.2 on 2024-03-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0004_alter_savingstransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
