# Generated by Django 5.0.2 on 2024-02-28 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0004_loanpayment_savingspayment_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='idnumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
