# Generated by Django 5.0.2 on 2024-02-28 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0006_merge_20240228_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savings',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='in_progress',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='purpose',
        ),
        migrations.AddField(
            model_name='item',
            name='savings',
            field=models.ManyToManyField(related_name='items', to='newmamapesa.savings'),
        ),
        migrations.AddField(
            model_name='savingsitem',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='savingsitem',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='savings',
            name='amount_saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingsitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_items', to='newmamapesa.item'),
        ),
    ]
