# Generated by Django 5.0.2 on 2024-02-28 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0006_remove_customuser_idnumber_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phonenumber',
        ),
    ]
