# Generated by Django 5.0.2 on 2024-02-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0007_customuser_interest_rate_customuser_loan_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='loan_limit',
            field=models.DecimalField(decimal_places=2, default=8000, max_digits=10),
        ),
    ]
