# Generated by Django 5.0.2 on 2024-02-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0007_remove_customuser_phonenumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savingspayment',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='savingspayment',
            name='savings_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_payments', to='newmamapesa.savingsitem'),
        ),
        migrations.AlterField(
            model_name='savingspayment',
            name='savings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_payments', to='newmamapesa.savings'),
        ),
    ]
