# Generated by Django 5.0.2 on 2024-03-08 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0008_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Currencies',
            },
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='fee',
            new_name='amount_deducted',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='grace_period_end_date',
            new_name='approval_date',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='interest_rate',
            new_name='deduction_rate',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='late_payment_penalty_rate',
            new_name='default_rate',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='disbursed',
            new_name='is_disbursed',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='collateral',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='grace_period',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='start_date',
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='default_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='payment_gateway',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='currency',
            field=models.ManyToManyField(related_name='payment_methods', to='newmamapesa.currency'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('trust_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN-REPAYMENT', 'Loan Repayment'), ('SAVINGS_DEPOSIT', 'Savings Deposit'), ('SUPPLIER_WITHDRAWAL', 'Supplier Withdrawal'), ('LOAN_SERVICE_CHARGE', 'Loan Service Charge')], max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='pending', max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newmamapesa.customer')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newmamapesa.loan')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='newmamapesa.paymentmethod')),
                ('savings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newmamapesa.savings')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
        migrations.DeleteModel(
            name='TrustScore',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
