# Generated by Django 5.0.2 on 2024-02-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0010_item_price_alter_savingsitem_target_amount'),
        ('newmamapesa', '0010_loanrepayment'),
    ]

    operations = [
    ]
