# Generated by Django 5.0.2 on 2024-03-09 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0011_communication'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='communication',
            table='Communications',
        ),
    ]
