# Generated by Django 5.0.2 on 2024-03-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0013_loan_loan_owed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_duration',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount_disbursed',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='collateral',
            field=models.FileField(blank=True, null=True, upload_to='collaterals/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='duration_months',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='loan',
            name='grace_period_months',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
