# Generated by Django 5.0.2 on 2024-03-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0013_customer_loan_limit_customer_loan_owed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='county',
        ),
    ]
