# Generated by Django 5.0.2 on 2024-03-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0014_remove_transaction_payment_method_loan_loan_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration_months',
            field=models.IntegerField(default=3, editable=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_duration',
            field=models.IntegerField(default=90, editable=False),
        ),
    ]
