# Generated by Django 5.0.2 on 2024-03-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0015_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
