# Generated by Django 5.0.2 on 2024-03-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0015_alter_loan_duration_months_alter_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='duration_months',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_duration',
            field=models.IntegerField(default=90),
        ),
    ]
