# Generated by Django 5.0.2 on 2024-03-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0016_alter_loan_duration_months_alter_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
    ]
