# Generated by Django 5.0.2 on 2024-03-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0017_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loan_owed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
