# Generated by Django 5.0.2 on 2024-03-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0018_customuser_loan_owed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='amount_disbursed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
