# Generated by Django 5.0.2 on 2024-03-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0018_alter_customer_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
