# Generated by Django 5.0.2 on 2024-03-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0019_alter_loan_amount_disbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='grace_period_remaining_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='remaining_days',
            field=models.IntegerField(default=0),
        ),
    ]
