# Generated by Django 5.0.2 on 2024-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0020_loan_grace_period_remaining_days_loan_remaining_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_limit',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=10),
        ),
    ]
