# Generated by Django 5.0.2 on 2024-03-05 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0021_loan_loan_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='overdue_rate',
            new_name='late_payment_penalty_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='grace_period_months',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='grace_period_remaining_days',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='installment_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_limit',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_owed',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='overdue_amount',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='penalty_rate',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='remaining_days',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='repayments',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_paid',
        ),
        migrations.AddField(
            model_name='loan',
            name='grace_period',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='loan',
            name='grace_period_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrepayment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INCOME', 'income'), ('EXPENSE', 'expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_successful', models.BooleanField(default=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_transactions', to='newmamapesa.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
