# Generated by Django 5.0.2 on 2024-02-28 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0002_remove_customuser_trustscore'),
        ('newmamapesa', '0005_alter_customuser_email'),
    ]

    operations = [
    ]
