# Generated by Django 5.0.2 on 2024-02-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0006_merge_20240228_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='loan_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
