# Generated by Django 5.0.2 on 2024-03-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0015_alter_savings_amount_saved_userdetails_withdrawal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
