# Generated by Django 5.0.2 on 2024-03-05 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0016_alter_savings_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savings', to=settings.AUTH_USER_MODEL),
        ),
    ]
